force-app/main/default/objects/BOT_Configuration_Value__mdt/BOT_Configuration_Value__mdt.object-meta.xml
<CustomObject>
    <description>This object is created by BusinessOne technologies Inc. It is used to store the configuration values like the default market, default pharmacy service, Endpoint URL etc</description>
    <label>BOT_Configuration Value</label>
    <pluralLabel>BOT_Configuration Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/BOT_Configuration_Value__mdt/fields/BOT_Value__c.field-meta.xml
<CustomField>
    <fullName>BOT_Value__c</fullName>
    <description>Used to hold the value.</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/BOT_Coverage_Policy__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the coverage policy details and having a lookup relationship with Account.</description>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Channel__c.field-meta.xml
<CustomField>
    <fullName>BOT_Channel__c</fullName>
    <description>For channel selection neither commercial or medicate</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_CP_Form_Available__c.field-meta.xml
<CustomField>
    <fullName>BOT_CP_Form_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if Coverage Policy form is available with the Account Plan.</description>
    <label>CP Form Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_DRC__c.field-meta.xml
<CustomField>
    <fullName>BOT_DRC__c</fullName>
    <description>Diagnostic Requirements for Continued Therapy Details</description>
    <label>Diagnostic Requirements for Continued</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_DRI__c.field-meta.xml
<CustomField>
    <fullName>BOT_DRI__c</fullName>
    <description>Diagnostic Requirements for Initial Therapy Details</description>
    <label>Diagnostic Requirements for Initial</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Drug_Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Drug_Policy_ID__c</fullName>
    <description>Used to Store the Policy ID.</description>
    <label>Drug Policy ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_ID__c</fullName>
    <description>To store the BOT Entity ID. It is used for BOT internal reference.</description>
    <label>Entity ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Formulary_Product__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product__c</fullName>
    <description>Master-Detail relationship to the Formulary Product object.</description>
    <label>Drug</label>
    <referenceTo>Formulary_Products_vod__c</referenceTo>
    <relationshipLabel>Coverage Policy</relationshipLabel>
    <relationshipName>Formulary_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>To store the BOT Drug ID. This field is used in Coverage Policy Before insert trigger to pull the SFDC Drug ID from the Formulary Product object.</description>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Indication__c.field-meta.xml
<CustomField>
    <fullName>BOT_Indication__c</fullName>
    <label>Indication</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_PA_Form_Available__c.field-meta.xml
<CustomField>
    <fullName>BOT_PA_Form_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if PA Form is available with the Account Plan.</description>
    <label>PA Form Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_PADetail__c.field-meta.xml
<CustomField>
    <fullName>BOT_PADetail__c</fullName>
    <label>PA Detail</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Poly_Therapy_Details__c.field-meta.xml
<CustomField>
    <fullName>BOT_Poly_Therapy_Details__c</fullName>
    <description>Poly Therapy Details</description>
    <label>Poly Therapy Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_STDetail__c.field-meta.xml
<CustomField>
    <fullName>BOT_STDetail__c</fullName>
    <label>Step Therapy Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Sub_Indication__c.field-meta.xml
<CustomField>
    <fullName>BOT_Sub_Indication__c</fullName>
    <label>Sub-Indication</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_SubChannel__c.field-meta.xml
<CustomField>
    <fullName>BOT_SubChannel__c</fullName>
    <description>To store the Sub Channel value</description>
    <label>SubChannel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_PA_CP_From_CofigValues__mdt/BOT_PA_CP_From_CofigValues__mdt.object-meta.xml
<CustomObject>
    <description>To hold the configuration values of the PA &amp; CP forms. Configuration values contain Base URL, Client Id, AppName, Version number, and secret key.</description>
    <label>PA&amp;CP From CofigValue</label>
    <pluralLabel>PA&amp;CP From CofigValues</pluralLabel>
</CustomObject>

force-app/main/default/objects/BOT_PA_CP_From_CofigValues__mdt/fields/BOT_AppName__c.field-meta.xml
<CustomField>
    <fullName>BOT_AppName__c</fullName>
    <description>to hold the Application Name</description>
    <label>AppName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_PA_CP_From_CofigValues__mdt/fields/BOT_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Client_Id__c</fullName>
    <description>To hold the client Id</description>
    <label>Client Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_PA_CP_From_CofigValues__mdt/fields/BOT_EndPoint_URL__c.field-meta.xml
<CustomField>
    <fullName>BOT_EndPoint_URL__c</fullName>
    <description>To hold the endpoint URL used to get the response.</description>
    <label>EndPoint URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_PA_CP_From_CofigValues__mdt/fields/BOT_SecretKey__c.field-meta.xml
<CustomField>
    <fullName>BOT_SecretKey__c</fullName>
    <label>SecretKey</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_PA_CP_From_CofigValues__mdt/fields/BOT_VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>BOT_VersionNumber__c</fullName>
    <label>VersionNumber</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulary_Products_vod__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>It is created by BusiessOne technologies. It is used to store BOT Drug ID.</description>
    <externalId>true</externalId>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BOT_CoveragePolicyViewExtn.cls
/*
Name 		 : BOT_CoveragePolicyViewExtn
Created Date : 12-Nov-2018
Created By   : Harsha BR
Overview 	 : It is written by BusinessOne Technologies Inc. It is used to fetch the coverage policy details. 
			   It pulls the PA or Covera policy form the external system based on user input.
			   
Modified by		: Sreenivasulu A
Modified Date	: 19-JUN-2019
Overview		: 1. Replaced the BOT_End_Point_PDF Custom label with custom metadata type field BOT_EndPoint_URL.
				  2. Added aditional parameters(client Id and Sub indication) to the end point URL.

Reviewed by		: Shridhar S
Modified Date	: 20-JUN-2019
Overview		: Added all Missing Parameters and also integrated with EndPoint URL to this.

*/
public class BOT_CoveragePolicyViewExtn
{   
    Public List<BOT_Coverage_Policy__c> lstCoveragePolicy{get;set;}	//To store the coverage policy records
    Public String type {get; set;}									//To store the form type PA/CP

    Public BOT_CoveragePolicyViewExtn(ApexPages.StandardController controller)
    {

        //To get the details of selected coverage policy
        lstCoveragePolicy=[SELECT Id, BOT_STDetail__c, BOT_DRC__c, BOT_DRI__c, BOT_PADetail__c, BOT_CP_Form_Available__c, BOT_PA_Form_Available__c, 
                           BOT_Entity_ID__c, BOT_Drug_Policy_ID__c, BOT_Formulary_Product_Id__c, BOT_Indication__c, BOT_Formulary_Product__r.Name,
                           BOT_Poly_Therapy_Details__c, BOT_Sub_Indication__c, BOT_Channel__c, BOT_SubChannel__c FROM BOT_Coverage_Policy__c
                           WHERE ID=:controller.getId() LIMIT 1];
    }
    
    //To get the PA Form or Coverage Policy From from the external system
    Public PageReference retrieveCPformPDF()
    {
        Decimal entityID=0;
        Decimal policyID=0;
        Decimal drugId=0;
        String indication;
        String subIndication ='';
        String channel;
        String subChannel;
        //Decimal clientId=0;
        //String baseURL;
        //String drugName;
        //String appName;
        //String versionNumber;
        //String secretKey;
        
        //System.debug('***type***: '+type);
        //String type = Apexpages.currentPage().getParameters().get('node');
		//System.debug('***type***: '+type);
        
        //String baseURL = Label.BOT_EndPointPDF;
        //baseURL = [SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_EndPoint_URL' LIMIT 1].BOT_Value__c;
        //clientId = Integer.valueOf([SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_Client_Id' LIMIT 1].BOT_Value__c);
        //appName = [SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_AppName' LIMIT 1].BOT_Value__c;
        //versionNumber = [SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_VersionNumber' LIMIT 1].BOT_Value__c;
        //secretKey = [SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_SecretKey' LIMIT 1].BOT_Value__c;
        
        /*
        if(lstCoveragePolicy[0].BOT_Formulary_Product__r.Name!=null)
        {
        	drugName=lstCoveragePolicy[0].BOT_Formulary_Product__r.Name;
            if(drugName.contains(' '))
            {
             	drugName=drugName.replaceAll(' ','%20');
            }
        }
		*/
        
        if(lstCoveragePolicy[0].BOT_Formulary_Product_Id__c!=null)
        {
        	drugId=lstCoveragePolicy[0].BOT_Formulary_Product_Id__c;
        }
        
        if(lstCoveragePolicy[0].BOT_Entity_ID__c!=null)
        {
         	entityID=lstCoveragePolicy[0].BOT_Entity_ID__c;  
        }
        if(lstCoveragePolicy[0].BOT_Channel__c!=null)
        {
         	channel=lstCoveragePolicy[0].BOT_Channel__c;
            if(channel.contains(' '))
            {
             	channel=channel.replaceAll(' ','%20');
            }
        }
        
        if(lstCoveragePolicy[0].BOT_SubChannel__c!=null)
        {
         	subChannel=lstCoveragePolicy[0].BOT_SubChannel__c;
            if(subChannel.contains(' '))
            {
             	subChannel=subChannel.replaceAll(' ','%20');
            }   
        }
        
        if(lstCoveragePolicy[0].BOT_Drug_Policy_ID__c!=null)
        {
         	policyID=lstCoveragePolicy[0].BOT_Drug_Policy_ID__c;   
          }
        
        if(lstCoveragePolicy[0].BOT_Indication__c!=null)
        {
         	indication=lstCoveragePolicy[0].BOT_Indication__c;
            if(indication.contains(' '))
            {
             	indication=indication.replaceAll(' ','%20');
            }   
        }
        
        if(lstCoveragePolicy[0].BOT_Sub_Indication__c!=null)
        {
         	subIndication=lstCoveragePolicy[0].BOT_Sub_Indication__c;
            if(subIndication.contains(' '))
            {
             	subIndication=subIndication.replaceAll(' ','%20');
            }   
        }
        
        //To get the configuration values from custom meta data object
        BOT_PA_CP_From_CofigValues__mdt objConfigValues = [SELECT Id, BOT_AppName__c, BOT_Client_Id__c, BOT_EndPoint_URL__c, BOT_SecretKey__c, 
                                                           BOT_VersionNumber__c FROM BOT_PA_CP_From_CofigValues__mdt
                                                           WHERE DeveloperName = 'Config_Values' LIMIT 1];
        
        Http h=new Http();
		HttpRequest req=new HttpRequest();
        String endPointURL = objConfigValues.BOT_EndPoint_URL__c+'?clientId='+Integer.valueOf(objConfigValues.BOT_Client_Id__c)+'&entityID='+entityID+
       						'&channel='+channel+'&subChannel='+subChannel+'&drugId='+drugId+'&documentType='+type+
            				'&drugpolicyid='+policyID+'&indicationname='+indication+'&subIndication='+subIndication+
        					'&VersionNumber='+objConfigValues.BOT_VersionNumber__c+'&AppName='+objConfigValues.BOT_AppName__c;
    	
        system.debug('***EndPoint***'+endPointURL);
        req.setEndpoint(endPointURL);
        req.setHeader('Content-Type','application/json');
    	req.setHeader('Content-Encoding','gzip'); 
        req.setHeader('document-api-key',objConfigValues.BOT_SecretKey__c); 
    	req.setMethod('GET');
        req.setTimeout(120000);
		HttpResponse res = h.send(req);
		system.debug('*** Response Body***'+res.getBody());
        BOT_CPFormResponse lstCPFormResponse = BOT_CPFormResponse.parse(res.getBody());
        system.debug('***lstCPFormResponse***'+lstCPFormResponse);
        PageReference pgref = new PageReference(lstCPFormResponse.fileURL);
		return pgref;
    }
}