force-app/main/default/objects/BOT_Configuration_Value__mdt/BOT_Configuration_Value__mdt.object-meta.xml
<CustomObject>
    <description>This object is created by BusinessOne technologies Inc. It is used to store the configuration values like the default market, default pharmacy service, Endpoint URL etc</description>
    <label>BOT_Configuration Value</label>
    <pluralLabel>BOT_Configuration Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/BOT_Configuration_Value__mdt/fields/BOT_Value__c.field-meta.xml
<CustomField>
    <fullName>BOT_Value__c</fullName>
    <description>Used to hold the value.</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/BOT_Coverage_Policy__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the coverage policy details and having a lookup relationship with Account.</description>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <description>Master-Detail relationship to the account object.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage policy</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Channel__c.field-meta.xml
<CustomField>
    <fullName>BOT_Channel__c</fullName>
    <description>For channel selection neither commercial or medicate</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Formulary_Product__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product__c</fullName>
    <description>Master-Detail relationship to the Formulary Product object.</description>
    <label>Drug</label>
    <referenceTo>Formulary_Products_vod__c</referenceTo>
    <relationshipLabel>Coverage Policy</relationshipLabel>
    <relationshipName>Formulary_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Indication__c.field-meta.xml
<CustomField>
    <fullName>BOT_Indication__c</fullName>
    <label>Indication</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Score__c.field-meta.xml
<CustomField>
    <fullName>BOT_Score__c</fullName>
    <label>Score</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Sub_Indication__c.field-meta.xml
<CustomField>
    <fullName>BOT_Sub_Indication__c</fullName>
    <label>Sub-Indication</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_SubChannel__c.field-meta.xml
<CustomField>
    <fullName>BOT_SubChannel__c</fullName>
    <description>To store the Sub Channel value</description>
    <label>SubChannel</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Formulary_Products_vod__c/fields/Market_vod__c.field-meta.xml
<CustomField>
    <fullName>Market_vod__c</fullName>
    <description>Market (such as Cholesterol Reducer) that this product belongs to.  This field is used as a filter in the formulary viewer.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Multiple Sclerosis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BOT_AccountCoveragePolicyExtn.cls
/*
Name            : BOT_AccountCoveragePolicyExtn
Created date    : 20-DEC-2018
Created by      : Sreenivasulu Adipudi
Description     :  This class is written by BusinessOne Technologies Inc. It is an extension of BOT_AccountCoveragePolicy Visualforce page.
*/
public with sharing class BOT_AccountCoveragePolicyExtn 
{
    ID accountId;                                                       //To store the ID of selected Account
    Public List<BOT_Coverage_Policy__c> lstCoveragePolicy {get;set;}    //To store the coverage policy records
    Public String strSelectedMarket {get; set;}                         //To store user selected market
    List<String> lstMarkets = new List<String>();                       //To store unique markets
    Public Integer intMarketCount {get;set;}							//To store number of market values present in the list
    ID documentId {get;set;}											//To store the Id of BOT logo document
    Public String strLogoUrl {get;set;}									//To store the URL of BOT logo with document Id
    
    //Constructor
    public BOT_AccountCoveragePolicyExtn(ApexPages.StandardController controller)
    {
        accountId = controller.getId();

        try 
        {
            //To create a list of markets associated with seleted Account's coverage policy
        	for(AggregateResult res : [SELECT BOT_Formulary_Product__r.Market_vod__c market FROM BOT_Coverage_Policy__c 
                                   	   GROUP BY BOT_Formulary_Product__r.Market_vod__c, BOT_Account__c HAVING BOT_Account__c =: accountId
                                       ORDER BY BOT_Formulary_Product__r.Market_vod__c])
        	{
        		lstMarkets.add(String.valueOf(res.get('market')));        
        	}
            //To get BOT logo document Id and Logo URL
            documentId = [SELECT Id FROM Document WHERE name = 'BusinessOne Logo' LIMIT 1].Id;
            strLogoUrl = [SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_Logo_URL' LIMIT 1].BOT_Value__c;
            strLogoUrl = strLogoUrl + documentId;
        }
        catch(Exception e) 
        {
        	system.debug('Exception '+e.getMessage()+ ' found in class BOT_AccountCoveragePolicyExtn at line number '+e.getLineNumber());
        }
        intMarketCount = lstMarkets.size();
        
        //Setting Default market value
        if(intMarketCount > 0)
        {
            //To get default market value from the custom label
        	//String strDefaultMarket = Label.BOT_DefaultMarket;
        	
            //To get default market value from the custom metadata object
            String strDefaultMarket = [SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_Default_Market' LIMIT 1].BOT_Value__c;
            
        	//If lstMarkets contains default maket value then set it as default
        	if(lstMarkets.contains(strDefaultMarket))
        	{
        		strSelectedMarket = strDefaultMarket;    
        	}
        	//else set the first value from the lstMarkets as default market
        	else
        	{
            	strSelectedMarket = lstMarkets[0];
        	}
        	//To get Coverage policy records related to selected account
        	getCoveragePolicyFilteredByMarket();
        }
    }
    
    public void getCoveragePolicy()
    {
        if(strSelectedMarket == 'All' || strSelectedMarket == null)
        {
            //To get Coverage policy records related to selected account
            lstCoveragePolicy = [SELECT Id, BOT_Channel__c, BOT_SubChannel__c, BOT_Formulary_Product__r.Name, BOT_Score__c, BOT_Indication__c, BOT_Sub_Indication__c 
                                 FROM BOT_Coverage_Policy__c WHERE BOT_Account__c =: accountId ORDER BY BOT_Formulary_Product__r.Name LIMIT 1000];
        }
        else
        {
            getCoveragePolicyFilteredByMarket();    
        }
    }
    
    public void getCoveragePolicyFilteredByMarket()
    {
        //To get Coverage policy records filtered by selected market
        lstCoveragePolicy = [SELECT Id, BOT_Channel__c, BOT_SubChannel__c,BOT_Formulary_Product__r.Name, BOT_Score__c, BOT_Indication__c, BOT_Sub_Indication__c 
                             FROM BOT_Coverage_Policy__c WHERE BOT_Account__c =: accountId AND BOT_Formulary_Product__r.Market_vod__c =: strSelectedMarket 
                             ORDER BY BOT_Formulary_Product__r.Name LIMIT 1000];
    }
    
    //To create dynamic market picklist values
    public list<selectOption> getDynamicList()
    {
        //return BOT_CreatePickListValues.getDynamicList(lstMarkets);
        List<selectOption> options = new List<selectOption>();
        if(intMarketCount > 0 && lstMarkets != null)
        {
            if(intMarketCount > 1)
            {
                options.add(new selectOption('All','All'));
            }
            for(String c : lstMarkets)
            {
                options.add(new selectOption(c,c));
            }            
        }
        return options;
    }
}