force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account type (e.g. Plan Provider, Network or Specialty Org). Used by MCO and MCO Plan accounts.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Admin Org</fullName>
            </value>
            <value>
                <fullName>Specialty Org</fullName>
            </value>
            <value>
                <fullName>Plan Provider</fullName>
            </value>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Stand-Alone Medicare</fullName>
            </value>
            <value>
                <fullName>Stand Alone HIX</fullName>
            </value>
            <value>
                <fullName>State Medicaid</fullName>
            </value>
            <value>
                <fullName>Specialty Provider</fullName>
            </value>
            <value>
                <fullName>Tricare</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>IDN</fullName>
            </value>
            <value>
                <fullName>ACO</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Person Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/BOT_Pharmacy_Service__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is Used to store the pharmacy services records and having a lookup relationship with Account.</description>
    <label>Pharmacy Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacy Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to Account. SFDC Account ID will be populated here.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pharmacy Services</relationshipLabel>
    <relationshipName>Pharmacy_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_ID__c</fullName>
    <description>To store the BOT Entity Id. it is used for BOT internal reference.</description>
    <label>Entity ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_PBM_Name__c.field-meta.xml
<CustomField>
    <fullName>BOT_PBM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to Account. SFDC PBM Account ID will be populated here.</description>
    <label>PBM Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pharmacy Services</relationshipLabel>
    <relationshipName>Pharmacy_Services_PBM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BOT_PharmacyServicesTriggerHandlerTest.cls
/*
Name            : BOT_PharmacyServicesTriggerHandlerTest
Created By      : Sreenivasulu A
Created Date    : 21-SEP-2018
Overview        : it is implemented by BusinessOne Technologies Inc.It is a test class of BOT_PharmacyServicesTriggerHandler.
*/
@isTest(seeAllData=false)
class BOT_PharmacyServicesTriggerHandlerTest 
{
    @testSetup static void createTestData()
    {
    	//To create the Account records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(5,'MCO');
		clsTestDataFactory.createAccountRecords(5,'PBM');

        //Test data validation
		system.assert([SELECT count() FROM Account WHERE Account_Type__c = 'MCO'] == 5);
        system.assert([SELECT count() FROM Account WHERE Account_Type__c = 'PBM'] == 5);
    }
    
    //Testing while creating a single Pharmacy service record
    static testMethod void createPharmacyService()
    {
        Account objAccount;								//To store an Account record
        Account objPBMAccount;							//To store a PBM Account record
        BOT_Pharmacy_Service__c objPharmacyService;		//To store a Pharmacy service record

        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();

        //To create a Pharmacy service record
        clsTestDataFactory.createPharmacyServices(1,1,'Formulary development/Admin');
        
        //Querying the created test data
        objAccount = [SELECT Id FROM Account WHERE Account_Type__c = 'MCO' ORDER BY BOT_Entity_Id__c LIMIT 1];
        objPBMAccount = [SELECT Id FROM Account WHERE Account_Type__c = 'PBM' ORDER BY BOT_Entity_Id__c LIMIT 1];
        objPharmacyService = [SELECT Id, BOT_Account__c, BOT_PBM_Name__c FROM BOT_Pharmacy_Service__c];
        
        //Test data validation
        system.assertEquals(objPharmacyService.BOT_Account__c, objAccount.Id);        
        system.assertEquals(objPharmacyService.BOT_PBM_Name__c, objPBMAccount.Id);
    }
    
    //Testing while creating a list of pharmacy service records
    static testMethod void createPharmacyServices()
    {
        List<Account> lstAccount;								//To store a List of Account records
        List<Account> lstPBMAccount;							//To store a List of PBM Account records
        List<BOT_Pharmacy_Service__c> lstPharmacyServices;		//To store a pharmacy services records
        Integer intTemp = 0;
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();

        //To create a list of Pharmacy service records
        clsTestDataFactory.createPharmacyServices(5,10,'Formulary development/Admin');
        clsTestDataFactory.createPharmacyServices(5,10,'Mail order');
        
        //Querying the created test data
        lstAccount = [SELECT Id FROM Account WHERE Account_Type__c = 'MCO'];
        lstPBMAccount = [SELECT Id FROM Account WHERE Account_Type__c = 'PBM'];
        lstPharmacyServices = [SELECT Id, BOT_Account__c, BOT_PBM_Name__c FROM BOT_Pharmacy_Service__c];
        
        //Test data validation
        system.assertEquals(lstAccount.size(), 5);
        system.assertEquals(lstPBMAccount.size(), 5);
        system.assertEquals(lstPharmacyServices.size(), 100);
        for(Integer i = 0; i < 5; i++)
        {
        	for(Integer j = 0; j < 10; j++)
            {
            	system.assertEquals(lstPharmacyServices[intTemp].BOT_Account__c, lstAccount[i].Id);        
        		system.assertEquals(lstPharmacyServices[intTemp].BOT_PBM_Name__c, lstPBMAccount[i].Id);
                intTemp++;
            }
        }
	}
    
    //Testing while creating a Pharmacy service Record without Entity Id
    static testMethod void singleRecordNegativeScenario()
    {
    	BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        try {
        	clsTestDataFactory.createPharmacyServicesWithoutEntityID(1,1,'Mail order');
        }
        catch(DMLException e) {
            system.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+
                                'Entity Id field is mandatory to save the record: []', e.getMessage());
        }
    }
}