force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account type (e.g. Plan Provider, Network or Specialty Org). Used by MCO and MCO Plan accounts.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Admin Org</fullName>
            </value>
            <value>
                <fullName>Specialty Org</fullName>
            </value>
            <value>
                <fullName>Plan Provider</fullName>
            </value>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Stand-Alone Medicare</fullName>
            </value>
            <value>
                <fullName>Stand Alone HIX</fullName>
            </value>
            <value>
                <fullName>State Medicaid</fullName>
            </value>
            <value>
                <fullName>Specialty Provider</fullName>
            </value>
            <value>
                <fullName>Tricare</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>IDN</fullName>
            </value>
            <value>
                <fullName>ACO</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Person Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Person_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Person_ID__c</fullName>
    <description>This field is created by BOT. It is used to store the unique ID of Key Contacts. It is an External ID and used for BOT internal reference.</description>
    <externalId>true</externalId>
    <label>Person ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/External_ID_vod__c.field-meta.xml
<CustomField>
    <fullName>External_ID_vod__c</fullName>
    <description>External ID is used for data loading only.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>120</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Child_Account_vod__c/fields/BOT_Affiliate_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Affiliate_Account_ID__c</fullName>
    <description>To store the BOT Affiliate Account ID (Entity ID/PersonID). It is used for BOT internal reference.</description>
    <label>Affiliate Account ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Child_Account_vod__c/fields/BOT_Parent_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Parent_Account_ID__c</fullName>
    <description>To store the BOT Parent Account ID (Entity ID/PBM ID). It is used for BOT internal reference.</description>
    <label>Parent Account ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Child_Account_vod__c/fields/BOT_Person_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Person_ID__c</fullName>
    <description>This field is created by BOT. It is used to store the key personId. This value is used for BOT internal reference.</description>
    <label>Person ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BOT_ChildAccountTriggerHandlerTest.cls
/*
Name            : BOT_ChildAccountTriggerHandlerTest
Created By      : Sreenivasulu A
Created Date    : 05-DEC-2018
Overview        : This class is written by BusinessOne Technologies Inc. It is a test class of BOT_ChildAccountTriggerHandler class.
*/
@isTest(seeAllData = false)
class BOT_ChildAccountTriggerHandlerTest 
{
	//To create the common test data
    @testSetup static void createTestData()
    {
    	//To create the Account records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(5,'MCO');
        clsTestDataFactory.createAccountRecords(5,'PBM');
		clsTestDataFactory.createPersonAccountRecords(5);
        
        //Test data validation
        system.assert([SELECT count() FROM Account WHERE Account_type__c = 'MCO'] == 5);
        system.assert([SELECT count() FROM Account WHERE Account_type__c = 'PBM'] == 5);
        system.assert([SELECT count() FROM Account WHERE Account_type__c = 'Person Account'] == 5);
    }
    
    //Testing while creating a Child Account record
    static testMethod void createChildAccount()
    {
    	Account objParentAccount;					//To store the Parent Account record
        Account objAffiliateAccount;				//To store the Affiliate Account record
        List<Child_Account_vod__c> lstChildAccount;	//To store the list of Child Account records returned by test data factory
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a Child Account record
        lstChildAccount = clsTestDataFactory.createChildAccountRecords(1,1);
       	insert lstChildAccount;
        
        //Querying the created test data
       	objParentAccount = [SELECT Id from Account WHERE Account_Type__c = 'PBM' ORDER BY BOT_Entity_ID__c LIMIT 1];
        objAffiliateAccount = [SELECT Id from Account WHERE Account_Type__c = 'MCO' ORDER BY BOT_Entity_ID__c LIMIT 1];
        lstChildAccount = [SELECT Parent_Account_vod__c, Child_Account_vod__c, External_ID_vod__c FROM Child_Account_vod__c];
        
        //Test data validation
        system.assertEquals(lstChildAccount[0].Child_Account_vod__c, objAffiliateAccount.Id);
        system.assertEquals(lstChildAccount[0].Parent_Account_vod__c, objParentAccount.Id);
        system.assertEquals(lstChildAccount[0].External_ID_vod__c, objParentAccount.Id + '__' + objAffiliateAccount.Id);
    }
    
    //Testing while creating a Child Person Account record
    static testMethod void createChildPersonAccount()
    {
    	Account objParentAccount;					//To store the Parent Account record
        Account objPersonAccount;					//To store the Person Account record
        List<Child_Account_vod__c> lstChildAccount;	//To store the list of Child Account records returned by test data factory
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a Child Person Account record
        lstChildAccount = clsTestDataFactory.createChildPersonAccountRecords(1,1);
       	insert lstChildAccount;
        
        //Querying the created test data
       	objParentAccount = [SELECT Id from Account WHERE Account_Type__c = 'MCO' ORDER BY BOT_Entity_ID__c LIMIT 1];
        objPersonAccount = [SELECT Id from Account WHERE Account_Type__c = 'Person Account' ORDER BY BOT_Person_ID__c LIMIT 1];
        lstChildAccount = [SELECT Parent_Account_vod__c, Child_Account_vod__c, External_ID_vod__c FROM Child_Account_vod__c];
        
        //Test data validation
        system.assertEquals(lstChildAccount[0].Child_Account_vod__c, objPersonAccount.Id);
        system.assertEquals(lstChildAccount[0].Parent_Account_vod__c, objParentAccount.Id);
        system.assertEquals(lstChildAccount[0].External_ID_vod__c, objParentAccount.Id + '__' + objPersonAccount.Id);
    }
    
    //Testing while creating the list of Child Account records
    static testMethod void createChildAccounts()
    {
    	List<Account> lstParentAccount;					//To store the list of Parent Account records
        List<Account> lstAffiliateAccount;				//To store the list of Affiliate Account records
        List<Child_Account_vod__c> lstChildAccount;		//To store a list of Child Account records returned by test data factory
        Integer intTemp = 0;
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a list of Child Account records
        lstChildAccount = clsTestDataFactory.createChildAccountRecords(5,5);
       	
       	insert lstChildAccount;
        
        //Querying the created test data
       	lstParentAccount = [SELECT Id from Account WHERE Account_Type__c = 'PBM' ORDER BY BOT_Entity_Id__c];
        lstAffiliateAccount = [SELECT Id from Account WHERE Account_Type__c = 'MCO' ORDER BY BOT_Entity_ID__c];
        lstChildAccount = [SELECT Parent_Account_vod__c, Child_Account_vod__c, External_ID_vod__c 
                           FROM Child_Account_vod__c ORDER BY BOT_Parent_Account_ID__c, BOT_Affiliate_Account_ID__c];
        
        //Test data validation
        system.assertEquals(lstParentAccount.size(), 5);
        system.assertEquals(lstAffiliateAccount.size(), 5);
        system.assertEquals(lstChildAccount.size(), 25);
        for(Integer i = 0; i < 5; i++)
        {
            for(Integer j = 0; j < 5; j++)
            {
            	system.assertEquals(lstChildAccount[intTemp].Child_Account_vod__c, lstAffiliateAccount[j].Id);
        		system.assertEquals(lstChildAccount[intTemp].Parent_Account_vod__c, lstParentAccount[i].Id);
                system.assertEquals(lstChildAccount[intTemp].External_ID_vod__c, lstParentAccount[i].Id + '__' + lstAffiliateAccount[j].Id);
                intTemp++;
            }
        }
    }
    
    //Testing while creating the list of Child Person Account records
    static testMethod void createChildPersonAccounts()
    {
    	List<Account> lstParentAccount;					//To store the list of Parent Account records
        List<Account> lstPersonAccount;					//To store the list of Person Account records
        List<Child_Account_vod__c> lstChildAccount;		//To store the list of Child Account records returned by test data factory
        Integer intTemp = 0;
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a list of Child Account records
        lstChildAccount = clsTestDataFactory.createChildPersonAccountRecords(5,5);
       	
       	insert lstChildAccount;

        //Querying the created test data
       	lstParentAccount = [SELECT Id from Account WHERE Account_Type__c = 'MCO' ORDER BY BOT_Entity_Id__c];
        lstPersonAccount = [SELECT Id from Account WHERE Account_Type__c = 'Person Account' ORDER BY BOT_Person_ID__c];
        lstChildAccount = [SELECT Parent_Account_vod__c, Child_Account_vod__c, External_ID_vod__c 
                           FROM Child_Account_vod__c ORDER BY BOT_Parent_Account_ID__c, BOT_Person_ID__c];
        
        //Test data validation
        system.assertEquals(lstParentAccount.size(), 5);
        system.assertEquals(lstPersonAccount.size(), 5);
        system.assertEquals(lstChildAccount.size(), 25);
        for(Integer i = 0; i < 5; i++)
        {
            for(Integer j = 0; j < 5; j++)
            {
            	system.assertEquals(lstChildAccount[intTemp].Child_Account_vod__c, lstPersonAccount[j].Id);
        		system.assertEquals(lstChildAccount[intTemp].Parent_Account_vod__c, lstParentAccount[i].Id);
                system.assertEquals(lstChildAccount[intTemp].External_ID_vod__c, lstParentAccount[i].Id + '__' + lstPersonAccount[j].Id);
                intTemp++;
            }
        }
    }

    
    //Testing while creating a Child Account records without BOT Entity ID
    static testMethod void createChildAccountWithoutEntityID()
    {
    	List<Child_Account_vod__c> lstChildAccount;	//To store a list of Child Account records returned by test data factory
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a Child Account records without BOT Entity ID
        lstChildAccount = clsTestDataFactory.createChildAccountRecords(5,5);
       	
        try{
        	insert lstChildAccount;
        }
        catch(DMLException e) {
            system.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+
                                'Entity Id and Person Account Id fields are mandatory to save the record: []', e.getMessage());
        }
    }
}