force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account type (e.g. Plan Provider, Network or Specialty Org). Used by MCO and MCO Plan accounts.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Admin Org</fullName>
            </value>
            <value>
                <fullName>Specialty Org</fullName>
            </value>
            <value>
                <fullName>Plan Provider</fullName>
            </value>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Stand-Alone Medicare</fullName>
            </value>
            <value>
                <fullName>Stand Alone HIX</fullName>
            </value>
            <value>
                <fullName>State Medicaid</fullName>
            </value>
            <value>
                <fullName>Specialty Provider</fullName>
            </value>
            <value>
                <fullName>Tricare</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>IDN</fullName>
            </value>
            <value>
                <fullName>ACO</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Person Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Is_BOT_Data__c.field-meta.xml
<CustomField>
    <fullName>BOT_Is_BOT_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It is created by BusinessOne Technologies. It indicates that record is created by BOT.</description>
    <label>Is BOT Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Parent_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Parent_Entity_ID__c</fullName>
    <description>To store the BOT parent entity ID. It is a hidden filed and used for BOT internal data reference.</description>
    <label>Parent Entity  ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Parent_vod__c.field-meta.xml
<CustomField>
    <fullName>Primary_Parent_vod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary parent of the account, as designated by the Account Hierarchy. The primary parent must be a business account.</description>
    <label>Primary Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Primary Parent</relationshipLabel>
    <relationshipName>Primary_Parent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BOT_UpdateAffiliateAccountsTest.cls
/*
Name            : BOT_UpdateAffiliateAccountsTest 
Created By      : Sreenivasulu A
Created Date    : 26-JUN-2019
Overview        : This class is written by BusinessOne Technologies Inc. It is a test class for BOT_UpdateAffiliateAccounts.
*/
@isTest
class BOT_UpdateAffiliateAccountsTest 
{
	//Testing while creating a Parent Account with one Affiliated record
    static TestMethod void createParentAndAffiliateAccount()
    {
        List<Account> lstAccount = new List<Account>();		//To store a Parent Account record and an Affiliate Account record
        Account objAffiliatedAccount = new Account();		//to store an Affiliated Account record
        
        //To create a Parent Account reocrd
        lstAccount.add(new Account(Name = 'Test Parent Account '+ 10000, BOT_Entity_ID__c = 10000, Account_Type__c = 'MCO', BOT_Is_BOT_Data__c = true));
        //To create an Affiliate Account reocrd
        lstAccount.add(new Account(Name = 'Test Child Account '+ 20000, BOT_Entity_ID__c = 20000, Account_Type__c = 'MCO', BOT_Is_BOT_Data__c = true, BOT_Parent_Entity_ID__c = 10000));
    	insert lstAccount;
        
        //To update affiliate Account with SFDC parent Account Id by using BOT_Parent_Entity_ID__c field
        BOT_UpdateAffiliateAccounts.updateAffiliateAccounts();
        
        //Querying the created test data
        objAffiliatedAccount = [SELECT Primary_Parent_vod__c, ParentId FROM Account WHERE BOT_Parent_Entity_ID__c != Null LIMIT 1];
        //Test data validation
        System.assertEquals(objAffiliatedAccount.Primary_Parent_vod__c , lstAccount[0].Id);
    }
    
    //Testing while creating the list of Parent Account with Affiliated records
    static TestMethod void createParentAndAffiliateAccounts()
    {
        List<Account> lstAccount = new List<Account>();				//To store the list of Parent Account records
        List<Account> lstAffliatedAccounts = new List<Account>();	//To store the list of Affiliated Account records
        Integer i, j, temp = 20000;
        
        //To create the list of Parent Account reocrds
        for(i = 10000; i < 10005; i++)
        {
        	lstAccount.add(new Account(Name = 'Test Parent Account '+ i, BOT_Entity_ID__c = i, Account_Type__c = 'MCO', BOT_Is_BOT_Data__c = true));    
        }
        
        //To create the list of Affiliated Account reocrds
        for(i = 10000; i < 10005; i++)
        {
            for(j = 20000; j < 20005; j++)
            {
        		lstAccount.add(new Account(Name = 'Test Child Account '+ temp, BOT_Entity_ID__c = temp, Account_Type__c = 'MCO', BOT_Is_BOT_Data__c = true, BOT_Parent_Entity_ID__c = i));
                temp++;
            }
        }        
    	insert lstAccount;
        
        //To update affiliate Accounts with SFDC parent Account Id by using BOT_Parent_Entity_ID__c field
        BOT_UpdateAffiliateAccounts.updateAffiliateAccounts();
        
        //Querying the created test data
        lstAccount = [SELECT Id FROM Account WHERE BOT_Parent_Entity_ID__c = Null ORDER BY BOT_Entity_ID__c];
        lstAffliatedAccounts = [SELECT Primary_Parent_vod__c, ParentId FROM Account WHERE BOT_Parent_Entity_ID__c != Null ORDER BY BOT_Parent_Entity_ID__c, BOT_Entity_ID__c];
        
        temp = 0;
        //Test data validation
        for(i = 0; i < 5; i++)
        {
            for(j = 0; j < 5; j++)
            {
            	System.assertEquals(lstAffliatedAccounts[temp].Primary_Parent_vod__c , lstAccount[i].Id);
                temp++;
            }
        }
    }
}