force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account type (e.g. Plan Provider, Network or Specialty Org). Used by MCO and MCO Plan accounts.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Admin Org</fullName>
            </value>
            <value>
                <fullName>Specialty Org</fullName>
            </value>
            <value>
                <fullName>Plan Provider</fullName>
            </value>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Stand-Alone Medicare</fullName>
            </value>
            <value>
                <fullName>Stand Alone HIX</fullName>
            </value>
            <value>
                <fullName>State Medicaid</fullName>
            </value>
            <value>
                <fullName>Specialty Provider</fullName>
            </value>
            <value>
                <fullName>Tricare</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>IDN</fullName>
            </value>
            <value>
                <fullName>ACO</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Person Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Parent_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Parent_Entity_ID__c</fullName>
    <description>To store the BOT parent entity ID. It is a hidden filed and used for BOT internal data reference.</description>
    <label>Parent Entity  ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Parent_vod__c.field-meta.xml
<CustomField>
    <fullName>Primary_Parent_vod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary parent of the account, as designated by the Account Hierarchy. The primary parent must be a business account.</description>
    <label>Primary Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Primary Parent</relationshipLabel>
    <relationshipName>Primary_Parent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BOT_AccountTriggerHandler.cls
/*
Name            : BOT_AccountTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 05-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc.It is used to update the RecordType ID's and
                  parent Salesforce ID's on the Child accounts.

Modified By 	:Harsha BR
Modified date 	:12-SEP-2018
Reason 			:Added comments and modified the code to follow the salesforce standard best practices.
*/
public with sharing class BOT_AccountTriggerHandler 
{
    //Used to autopoplate the record type Id and SFDC Parent Id.
    public static void updateRecordtypeID(List<Account> lstAccounts)
    {
        Map<String, Id> mapRecordtypeIds = new Map<String, Id>();		//Used to store the Record type name and its associated salesforce ID
        
        //To Retrieve SFDC RecordTypeId by comparing Account, Channel and put in the map
        for(RecordType objRecordTypeId : [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Account' AND Name LIKE 'BOT%' LIMIT 50000])
        {
            mapRecordtypeIds.put(objRecordTypeId.Name.toUpperCase(), objRecordTypeId.Id);
        }
		
        //Updating appropriate recordTypeId
        for(Account objAccount : lstAccounts)
        {             
            objAccount.RecordTypeId = mapRecordtypeIds.get('BOT '+objAccount.Account_Type__c.toUpperCase());
        }
    }
    
    //Used to autopoplate the SFDC Parent Id.
    public static void updateParentID(List<Account> lstAccounts, Set<Integer> setEntityParentIds)
    {
    	Map<Integer, Id> mapEntityParentIds = new Map<Integer, Id>();	//Used to store the BOT Entity ID and its associated salesforce ID
        
        //To Retrieve SFDC Parent Id by comparing BOT parent Entity Id and put in the map
        for(Account objAccount : [SELECT Id, BOT_Entity_Id__c FROM Account WHERE BOT_Entity_Id__c in : setEntityParentIds LIMIT 50000])
        {
        	mapEntityParentIds.put(Integer.valueOf(objAccount.BOT_Entity_Id__c), objAccount.Id);
        }
        
        //Updating appropriate SFDC Parent entity ID
        for(Account objAccount : lstAccounts)
        {             
        	objAccount.Primary_Parent_vod__c = mapEntityParentIds.get(Integer.valueOf(objAccount.BOT_Parent_Entity_ID__c));
            objAccount.ParentId = objAccount.Primary_Parent_vod__c;
        }
    }
}