force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account type (e.g. Plan Provider, Network or Specialty Org). Used by MCO and MCO Plan accounts.</description>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PBM</fullName>
            </value>
            <value>
                <fullName>Network</fullName>
            </value>
            <value>
                <fullName>Admin Org</fullName>
            </value>
            <value>
                <fullName>Specialty Org</fullName>
            </value>
            <value>
                <fullName>Plan Provider</fullName>
            </value>
            <value>
                <fullName>MCO</fullName>
            </value>
            <value>
                <fullName>Stand-Alone Medicare</fullName>
            </value>
            <value>
                <fullName>Stand Alone HIX</fullName>
            </value>
            <value>
                <fullName>State Medicaid</fullName>
            </value>
            <value>
                <fullName>Specialty Provider</fullName>
            </value>
            <value>
                <fullName>Tricare</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>IDN</fullName>
            </value>
            <value>
                <fullName>ACO</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Person Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Thera_Class__c/BOT_Thera_Class__c.object-meta.xml
<CustomObject>
    <description>(BOT)It is created by BusinessOne Technologies Inc. It is used to store the Therapeutic Class with associated specialty provider Account.</description>
    <label>Therapeutic Class</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Thera_Class__c/fields/BOT_Specialty_Provider__c.field-meta.xml
<CustomField>
    <fullName>BOT_Specialty_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It is a Lookup relationship to Account (Specialty provider)</description>
    <label>Specialty Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Thera_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Thera_Class__c/fields/BOT_Specialty_Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Specialty_Provider_ID__c</fullName>
    <description>To store the BOT Specialty Provider ID (Entity ID). It is used for BOT internal reference.</description>
    <label>Specialty Provider ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BOT_TheraClassTriggerHandlerTest.cls
/*
Name            : BOT_TheraClassTriggerHandlerTest
Created By      : Sreenivasulu A
Created Date    : 25-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a test class of BOT_TheraClassTriggerHandler class.
*/
@isTest(seeAllData = false)
class BOT_TheraClassTriggerHandlerTest 
{
    @testSetup static void createTestData()
    {
    	//To create the Account records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(5,'Specialty Provider');
        
        //Test data validation
        system.assert([SELECT count() FROM Account WHERE Account_type__c = 'Specialty Provider'] == 5);
    }
    
    //Testing while creating a Thera class record
    static testMethod void createTheraClassRecord()
    {
       	Account objSpecialtyProvider;     		//To store a Specilary provider Account record
        List<BOT_Thera_Class__c> lstTheraClass; //To store a list of Thera class records returned by test data factory
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        //To create a Thera class record
        lstTheraClass = clsTestDataFactory.createTheraClassWithSpecialtyId(1,1);
       	insert lstTheraClass;
        
        //Querying the created test data
        objSpecialtyProvider = [SELECT Id FROM Account ORDER BY BOT_Entity_ID__c LIMIT 1];
        lstTheraClass = [SELECT Id, BOT_Specialty_Provider__c FROM BOT_Thera_Class__c LIMIT 1];
        
        //Test data validation
        system.assertEquals(lstTheraClass[0].BOT_Specialty_Provider__c, objSpecialtyProvider.Id);
    }
    
    //To create a list of Thera class records
    static testMethod void createTheraClassRecords()
    {
       	List<Account> lstSpecialtyProvider;     //To store a list of Specilary provider Account records
        List<BOT_Thera_Class__c> lstTheraClass; //To store a list of Thera class records returned by test data factory
        Integer intTemp = 0;
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        //To create a list of Thera class records
        lstTheraClass = clsTestDataFactory.createTheraClassWithSpecialtyId(5,5);
       	insert lstTheraClass;        
        
        //Querying the created test data
        lstSpecialtyProvider = [SELECT Id FROM Account ORDER BY BOT_Entity_ID__c];
        lstTheraClass = [SELECT Id, BOT_Specialty_Provider__c FROM BOT_Thera_Class__c ORDER BY BOT_Specialty_Provider_ID__c];
        
        //Test data validation
       	system.assertEquals(lstSpecialtyProvider.size(), 5);
        system.assertEquals(lstTheraClass.size(), 25);
        for(Integer i = 0; i < 5; i++)
        {
            for(Integer j = 0; j < 5; j++)
            {
	        	system.assertEquals(lstTheraClass[intTemp].BOT_Specialty_Provider__c, lstSpecialtyProvider[i].Id);
                intTemp++;
            }
        }
    }
    
    //Testing while creating a Thera class record without Specialty provider Id
    static testMethod void createTheraClassWithoutSpecialtyId()
    {
        List<BOT_Thera_Class__c> lstTheraClass; //To store a list of Thera class records returned by test data factory
       	BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
		
        //To create a Thera class record
        lstTheraClass = clsTestDataFactory.createTheraClassWithoutSpecialtyId(1,1);
        try {
        	insert lstTheraClass;
        }
        catch(DMLException e) {
            system.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+
                                'Specialty provider Id field is mandatory to save the record: []', e.getMessage());
        }
    }
}