force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Thera_Class__c/BOT_Thera_Class__c.object-meta.xml
<CustomObject>
    <description>(BOT)It is created by BusinessOne Technologies Inc. It is used to store the Therapeutic Class with associated specialty provider Account.</description>
    <label>Therapeutic Class</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Thera_Class__c/fields/BOT_Specialty_Provider__c.field-meta.xml
<CustomField>
    <fullName>BOT_Specialty_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>It is a Lookup relationship to Account (Specialty provider)</description>
    <label>Specialty Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Thera_Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Thera_Class__c/fields/BOT_Specialty_Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Specialty_Provider_ID__c</fullName>
    <description>To store the BOT Specialty Provider ID (Entity ID). It is used for BOT internal reference.</description>
    <label>Specialty Provider ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BOT_TheraClassTriggerHandler.cls
/*
Name            : BOT_TheraClassTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 25-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a handler class of BOT_TheraClassTrigger trigger.
*/
public with sharing class BOT_TheraClassTriggerHandler 
{
	public static void populateSpecialtyProviderIds(List<BOT_Thera_Class__c> lstTheraClass, Set<Integer> setSpecialtyProviderIds)
    {
    	Map<Integer,ID> mapSpecialtyProviderIds = new Map<Integer, ID>();	//To store BOT Specialty ProviderId and Salesforce Specialty Provider Id
        
        //Retrieveing SFDC Account Id by comparing BOT_Entity_Id__c with SPP Id and put it in the map
        for(Account objAccount : [SELECT Id, BOT_Entity_Id__c FROM Account WHERE BOT_Entity_Id__c in : setSpecialtyProviderIds LIMIT 50000])
        {
        	mapSpecialtyProviderIds.put(Integer.valueOf(objAccount.BOT_Entity_Id__c), objAccount.Id);
        }
        
       	//To populate the BOT_Specialty_Provider__c field
        for(BOT_Thera_Class__c objTheraClass : lstTheraClass)
        {
            objTheraClass.BOT_Specialty_Provider__c = mapSpecialtyProviderIds.get(Integer.valueOf(objTheraClass.BOT_Specialty_Provider_ID__c));
        }    
    }
}