force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/BOT_Drug_Access__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the drug access percentage.</description>
    <label>Drug Access</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drug Access</relationshipLabel>
    <relationshipName>Drug_Access</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Formulary_Product__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to formulary product (Drug) object.</description>
    <label>Drug Name</label>
    <referenceTo>Formulary_Products_vod__c</referenceTo>
    <relationshipLabel>Drug Access</relationshipLabel>
    <relationshipName>Drug_Access</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>To store the BOT Formulary Product (Drug) ID. It is used for BOT internal reference.</description>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulary_Products_vod__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>It is created by BusiessOne technologies. It is used to store BOT Drug ID.</description>
    <externalId>true</externalId>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Formulary_Products_vod__c/fields/Market_vod__c.field-meta.xml
<CustomField>
    <fullName>Market_vod__c</fullName>
    <description>Market (such as Cholesterol Reducer) that this product belongs to.  This field is used as a filter in the formulary viewer.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Multiple Sclerosis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BOT_DrugAccessTriggerHandlerTest.cls
/*
Name            : BOT_DrugAccessTriggerHandlerTest
Created By      : Sreenivasulu A
Created Date    : 21-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a test class of BOT_DrugAccessTriggerHandler class.
*/
@isTest(seeAllData=false)
class BOT_DrugAccessTriggerHandlerTest 
{
    @testSetup static void createTestData()
    {
    	//To create the Account and Fromulary product records
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        clsTestDataFactory.createAccountRecords(5,'Employer');
        clsTestDataFactory.createFormularyProductRecords(5);
        
        //Test data validation
        system.assert([SELECT count() FROM Account] == 5);
        system.assert([SELECT count() FROM Formulary_Products_vod__c] == 5);
    }
    
    //Testing while creating a single Drug Access record
    static testMethod void createDrugAccessRecord()
    {
        Account objAccount;                                 //To store an Account record
        Formulary_Products_vod__c objFormularyProduct;      //To store a formulary product record
        List<BOT_Drug_Access__c> lstDrugAccess;             //To store a list of drug access records returned by test data factory
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        //To create a Drug access record
        lstDrugAccess = clsTestDataFactory.createDrugAccessRecords(1, 1);
       	insert lstDrugAccess;
        
        //Querying the created test data
        objAccount = [SELECT Id FROM Account ORDER BY BOT_Entity_Id__c LIMIT 1];
        objFormularyProduct = [SELECT Id, Market_vod__c FROM Formulary_products_vod__c ORDER BY BOT_Formulary_Product_ID__c LIMIT 1];
        lstDrugAccess = [SELECT Id, Name, BOT_Account__c, BOT_Formulary_Product__c FROM BOT_Drug_Access__c];
        
        //Test data validation
        system.assertEquals(lstDrugAccess[0].Name,objFormularyProduct.Market_vod__c);
        system.assertEquals(lstDrugAccess[0].BOT_Account__c, objAccount.Id);
        system.assertEquals(lstDrugAccess[0].BOT_Formulary_Product__c, objFormularyProduct.Id);
    }
    
    //Testing while creating a list of Drug Access records
    static testMethod void createDrugAccessRecords()
    {
        List<Account> lstAccount;                           	//To store a list of Account records
        List<Formulary_Products_vod__c> lstFormularyProduct;    //To store a list of formulary product records
        List<BOT_Drug_Access__c> lstDrugAccess;                 //To store a list of drug access records returned by test data factory
        Integer intTemp = 0;
        
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a list of Drug access records
        lstDrugAccess = clsTestDataFactory.createDrugAccessRecords(5, 5);
       	insert lstDrugAccess;
        
        //Querying the created test data
        lstAccount = [SELECT Id FROM Account ORDER BY BOT_Entity_Id__c];
        lstFormularyProduct = [SELECT Id, Market_vod__c FROM Formulary_products_vod__c ORDER BY BOT_Formulary_Product_ID__c];
        lstDrugAccess = [SELECT Id, Name, BOT_Account__c, BOT_Formulary_Product__c FROM BOT_Drug_Access__c ORDER BY BOT_Entity_Id__c];
        
        //Test data validation
        system.assertEquals(lstAccount.size(), 5);
        system.assertEquals(lstFormularyProduct.size(), 5);
        system.assertEquals(lstDrugAccess.size(), 25);
        for(Integer i = 0; i < 5; i++)
        {
        	for(Integer j = 0; j < 5; j++)
            {
            	system.assertEquals(lstDrugAccess[intTemp].BOT_Account__c, lstAccount[i].Id);
                system.assertEquals(lstDrugAccess[intTemp].BOT_Formulary_Product__c, lstFormularyProduct[j].Id);    
                system.assertEquals(lstDrugAccess[intTemp].Name,lstFormularyProduct[j].Market_vod__c);
                intTemp++;
            }
        }
    }
    
    //Testing while creating a Drug access record with out Entity Id
    static testMethod void createDrugAccessWithoutEntityID()
    {	
    	List<BOT_Drug_Access__c> lstDrugAccess;		//To store a list of drug access records returned by test data factory
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a Drug access record without Entity Id
        lstDrugAccess = clsTestDataFactory.createDrugAccessWithoutEntityID(1,1);
        try {
        	insert lstDrugAccess;    
        }
        catch(DMLException e) {
            system.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+
                                'Entity Id and Formulary Product Id fields are required to save the record: []', e.getMessage());
        }
    }
    
    //Testing while creating a Drug access record with out Formualry Product Id
    static testMethod void createDrugAccessWithoutFormualryProductID()
    {	
    	List<BOT_Drug_Access__c> lstDrugAccess;		//To store a list of drug access records returned by test data factory
        BOT_TestDataFactory clsTestDataFactory = new BOT_TestDataFactory();
        
        //To create a Drug access record without Formulary Product Id
        lstDrugAccess = clsTestDataFactory.createDrugAccessWithoutFormualryProductID(1,1);
        try {
        	insert lstDrugAccess;    
        }
        catch(DMLException e) {
            system.assertEquals('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+
                                'Entity Id and Formulary Product Id fields are required to save the record: []', e.getMessage());
        }
    }    
}