force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/BOT_Plan_Product__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the Plan product information and having a lookup relationship with Account.</description>
    <label>Plan Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <description>Master-detail relationship to Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plan Products</relationshipLabel>
    <relationshipName>Plan_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_ID__c</fullName>
    <description>To store the BOT Entity Id. It is used for BOT internal reference.</description>
    <label>Entity ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Medical_Admin__c.field-meta.xml
<CustomField>
    <fullName>BOT_Medical_Admin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to Account. This field represents the medical administrator.</description>
    <label>Medical Admin</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plan Products (Medical Admin)</relationshipLabel>
    <relationshipName>Medical_Admin</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Medical_Admin_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Medical_Admin_ID__c</fullName>
    <description>To store the BOT medical admin ID(Entity ID). It is used for BOT internal reference only.</description>
    <label>Medical Admin ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BOT_PlanProductTriggerHandler.cls
/*
Name			: BOT_PlanProductTriggerHandler
Created By		: Sreenivasulu A
Created Date	: 14-AUG-2018
Overview		: This class is written by BusinessOne Technologies Inc. It is handler class of BOT_PlanProductTrigger trigger.
				  1. It is used to handle the name where having morethan 80 characters.
				  2. It populates the BOT_Account__c field.
				  3. It populates the BOT_Medical_Admin__c filed.

Modified By 	:Harsha BR
Modified date 	:12-SEP-2018
Reason 			:Added comments and modified the code to follow the salesforce standard best practices.

Modified by		: Sreenivasulu A
Modified date	: 09-OCT-2018
Reason			: Added data update functionility. It updates the BOT_Account__c field and BOT_Medical_Admin__c field when the record is created or updated.
*/
public with sharing class BOT_PlanProductTriggerHandler 
{
    //To populate SFDC Account ID and Manage the name field
    public static void manageNameAndPopulateAccountId(List<BOT_Plan_Product__c> lstPlanProducts, Set<Integer> setEntityIds)
    {
        Map<Integer, ID> mapAccountIds = new Map<Integer,ID>();		//To store BOT Entity Ids and SFDC Ids of Account object
        
        //To Retrieve SFDC Account Id by comparing BOT Entity Id and put in the map
        for(Account objAccount : [SELECT ID, BOT_Entity_ID__c FROM Account WHERE BOT_Entity_ID__c in : setEntityIds])
        {
            mapAccountIds.put(Integer.valueOf(objAccount.BOT_Entity_ID__c), objAccount.Id);
        }
		
        for(BOT_Plan_Product__c objPlanProduct : lstPlanProducts)
        {
            //Populating BOT_Account__c field value
            objPlanProduct.BOT_Account__c = mapAccountIds.get(Integer.valueOf(objPlanProduct.BOT_Entity_ID__c));
        }
    }
    
    //To populate SFDC Medical Admin Id (Account Id)
    public static void updateMedicalAdminIds(List<BOT_Plan_Product__c> lstPlanProducts, set<Integer> setMedicalAdminIds)
    {
        Map<Integer, ID> mapAccountIds = new Map<Integer,ID>();				//To store BOT Entity Ids and SFDC Account Ids of Account object

        //To Retrieve SFDC Medical Admin Id by comparing BOT Medical Admin Id and put in the map
        for(Account objAccount : [SELECT Id, BOT_Entity_ID__c FROM Account WHERE BOT_Entity_ID__c in : setMedicalAdminIds])
        {
            mapAccountIds.put(Integer.valueOf(objAccount.BOT_Entity_ID__c), objAccount.Id);
        }
		
        for(BOT_Plan_Product__c objPlanProduct : lstPlanProducts)
        {
            //Populating BOT_Medical_Admin__c field value
            objPlanProduct.BOT_Medical_Admin__c = mapAccountIds.get(Integer.valueOf(objPlanProduct.BOT_Medical_Admin_ID__c));
        }   
    }
}