force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/BOT_Pharmacy_Service__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is Used to store the pharmacy services records and having a lookup relationship with Account.</description>
    <label>Pharmacy Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacy Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to Account. SFDC Account ID will be populated here.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pharmacy Services</relationshipLabel>
    <relationshipName>Pharmacy_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_ID__c</fullName>
    <description>To store the BOT Entity Id. it is used for BOT internal reference.</description>
    <label>Entity ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_PBM_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_PBM_ID__c</fullName>
    <description>To store the BOT PBM ID. It is used for BOT internal reference.</description>
    <label>PBM_ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_PBM_Name__c.field-meta.xml
<CustomField>
    <fullName>BOT_PBM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to Account. SFDC PBM Account ID will be populated here.</description>
    <label>PBM Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pharmacy Services</relationshipLabel>
    <relationshipName>Pharmacy_Services_PBM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BOT_PharmacyServicesTriggerHandler.cls
/*
Name            : BOT_PharmacyServicesTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 07-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a handler class of BOT_PharmacyServicesTrigger
				  It is used to populate the SFDC Account ID by using BOT Entity ID.

Modified By   : Harsha BR
Modified Date : 14-SEP-2018
Reason        : To move the business logic to the Apex class and to follow the naming conventions.
*/

public with sharing class BOT_PharmacyServicesTriggerHandler 
{
	public static void populateAccountAndPbmIds(List<BOT_Pharmacy_Service__c> lstPharmacyServices, Set<Integer> setBOTAccountIds)
    {
        Map<Integer, ID> mapAccountIds = new Map<Integer, ID>();	//To store the map of BOT Entity ID and Salesforce account ID
        
    	//Retrieving SFDC Account Id by comparing BOT Entity Id or BOT PBM Id 
        for(Account objAccount : [SELECT Id, BOT_Entity_Id__c FROM Account WHERE BOT_Entity_Id__c in : setBOTAccountIds])
        {
        	mapAccountIds.put(Integer.valueOf(objAccount.BOT_Entity_Id__c), objAccount.Id);   
        }
        
        //To populate BOT_Account__c and BOT_PBM_Name__c fileds
        for(BOT_Pharmacy_Service__c objPharmacyService : lstPharmacyServices)
        {
        	objPharmacyService.BOT_Account__c = mapAccountIds.get(Integer.valueOf(objPharmacyService.BOT_Entity_ID__c));
            
            if(objPharmacyService.BOT_PBM_ID__c != Null)
            {
            	objPharmacyService.BOT_PBM_Name__c = mapAccountIds.get(Integer.valueOf(objPharmacyService.BOT_PBM_ID__c));
            }
        }
    }
}