force-app/main/default/objects/Account/fields/BOT_Suffix1__c.field-meta.xml
<CustomField>
    <fullName>BOT_Suffix1__c</fullName>
    <label>Suffix1</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Suffix_vod__c.field-meta.xml
<CustomField>
    <fullName>Suffix_vod__c</fullName>
    <description>Suffix.  Used for person accounts.</description>
    <label>Suffix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BOT_ClonePersonAccountExtn.cls
/* 
Name            : BOT_ClonePersonAccountExtn
Created by      : Sreenivasulu Adipudi
Created Date    : 20-MAR-2019
Description     : This class is written by BusinessOne Technologies Inc. It is a extension class of BOT_ClonePersonAccount Visualforce page.
*/
public class BOT_ClonePersonAccountExtn 
{
	public String strPersonAccountId;
    Account objAccount;
    Contact objContact;
    public BOT_ClonePersonAccountExtn(ApexPages.StandardController controller)
    {
        strPersonAccountId = controller.getId();
        objAccount = [SELECT Id, FirstName, LastName, Suffix_vod__c, BOT_Suffix1__c, PersonMailingStreet, PersonMailingCity, 
                      PersonMailingState, PersonMailingPostalCode, Phone from Account WHERE Id =: strPersonAccountId];
        objContact.AccountId = objAccount.Id;
        objContact.FirstName = objAccount.FirstName;
        objContact.LastName = objAccount.LastName;
    }
}