force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/BOT_Coverage_Policy__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the coverage policy details and having a lookup relationship with Account.</description>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <description>Master-Detail relationship to the account object.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage policy</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_ID__c</fullName>
    <description>To store the BOT Entity ID. It is used for BOT internal reference.</description>
    <label>Entity ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Formulary_Product__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product__c</fullName>
    <description>Master-Detail relationship to the Formulary Product object.</description>
    <label>Drug</label>
    <referenceTo>Formulary_Products_vod__c</referenceTo>
    <relationshipLabel>Coverage Policy</relationshipLabel>
    <relationshipName>Formulary_Product</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>To store the BOT Drug ID. This field is used in Coverage Policy Before insert trigger to pull the SFDC Drug ID from the Formulary Product object.</description>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulary_Products_vod__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>It is created by BusiessOne technologies. It is used to store BOT Drug ID.</description>
    <externalId>true</externalId>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BOT_CoveragePolicyTriggerHandler.cls
/*
Name            : BOT_CoveragePolicyTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 04-FEB-2019
Overview        : It is implemented by BusinessOne Technologies Inc. It is a handler class of BOT_CoveragePolicyTrigger.
*/
public class BOT_CoveragePolicyTriggerHandler 
{
	public static void populateAccountAndProductIds(List<BOT_Coverage_Policy__c> lstCoveragePolicy, Set<Integer> setBOTEntityIds, Set<Integer> setBOTFormularyproductIds)
    {
        Map<Integer, ID> mapAccountIds = new Map<Integer, ID>();	//To store BOT Entity ID and asssociated SFDC Account ID
        Map<Integer, ID> mapFormularyProductIds;					//To store BOT Formulary Product ID and asssociated SFDC Formulary Product ID
        
        //Retrieving SFDC Accout Ids by comparing BOT Entity Ids and put in the map 
        for(Account objAccount : [SELECT Id, BOT_Entity_ID__c FROM Account WHERE BOT_Entity_ID__c IN : setBOTEntityIds LIMIT 50000])
        {
        	mapAccountIds.put(Integer.valueOf(objAccount.BOT_Entity_ID__c), objAccount.Id);
        }
        
        //Retrieving SFDC Formulary product Id by comparing BOT Formulary Product ID and put in the map
        mapFormularyProductIds = new Map<Integer, Id>();
        for(Formulary_Products_vod__c objFormularyProduct : [SELECT Id, BOT_Formulary_Product_ID__c FROM Formulary_Products_vod__c WHERE BOT_Formulary_Product_ID__c IN : setBOTFormularyproductIds LIMIT 50000])
        {
        	mapFormularyProductIds.put(Integer.valueOf(objFormularyProduct.BOT_Formulary_Product_ID__c), objFormularyProduct.Id);
        }
        
        //To populate BOT_Account__c, BOT_Formulary_Product__c fileds of the Coverage Policy object
        for(BOT_Coverage_Policy__c objCoveragePolicy : lstCoveragePolicy)
        {
            objCoveragePolicy.BOT_Account__c = mapAccountIds.get(Integer.valueOf(objCoveragePolicy.BOT_Entity_ID__c));
            objCoveragePolicy.BOT_Formulary_Product__c = mapFormularyProductIds.get(Integer.valueOf(objCoveragePolicy.BOT_Formulary_Product_ID__c));
        }
    }
}