force-app/main/default/objects/Account/fields/BOT_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>BOT_Entity_Id__c</fullName>
    <description>To store BOT Entity Id. It is used for internal reference, it is unique also using as external Id. It is a hidden field and will not appear in page layout.</description>
    <externalId>true</externalId>
    <label>Entity Id</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/BOT_Drug_Access__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the drug access percentage.</description>
    <label>Drug Access</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drug Access</relationshipLabel>
    <relationshipName>Drug_Access</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Formulary_Product__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to formulary product (Drug) object.</description>
    <label>Drug Name</label>
    <referenceTo>Formulary_Products_vod__c</referenceTo>
    <relationshipLabel>Drug Access</relationshipLabel>
    <relationshipName>Drug_Access</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>To store the BOT Formulary Product (Drug) ID. It is used for BOT internal reference.</description>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Formulary_Products_vod__c/fields/BOT_Formulary_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product_ID__c</fullName>
    <description>It is created by BusiessOne technologies. It is used to store BOT Drug ID.</description>
    <externalId>true</externalId>
    <label>Formulary Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Formulary_Products_vod__c/fields/Market_vod__c.field-meta.xml
<CustomField>
    <fullName>Market_vod__c</fullName>
    <description>Market (such as Cholesterol Reducer) that this product belongs to.  This field is used as a filter in the formulary viewer.</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Multiple Sclerosis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BOT_DrugAccessTriggerHandler.cls
/*
Name            : BOT_DrugAccessTriggerHandler
Created By      : Sreenivasulu A
Created Date    : 07-SEP-2018
Overview        : It is implemented by BusinessOne Technologies Inc.It is a handler class to BOT_DrugAccessTrigger trigger. 
				  It is used to populate the SFDC Account ID and SFDC Formulary Product ID by comparing BOT Entity ID and BOT Drug ID respectively.

Modified By 	:Harsha BR
Modified date 	:12-SEP-2018
Reason 			:Added comments and modified the code to follow the salesforce standard best practices.
*/
public with sharing class BOT_DrugAccessTriggerHandler 
{
	public static void populateAccountAndProductIds(List<BOT_Drug_Access__c> lstDrugAccess, Set<Integer> setBOTEntityIds, Set<Integer> setBOTFormularyproductIds)
    {
        Map<Integer, ID> mapAccountIds;										//Map of BOT Entity ID and its asssociated SFDC Account ID
        Map<Integer, Formulary_Products_vod__c> mapFormularyProduct;		//Map of BOT Formulary Product ID and formulary product record
        Formulary_Products_vod__c objFormularyProduct1;						//To store a formulary product record;
        
        //To Retrieve SFDC Accout Ids by comparing BOT Account Ids and put in the map 
        mapAccountIds = new Map<Integer, ID>();
        for(Account objAccount : [SELECT Id, BOT_Entity_ID__c FROM Account WHERE BOT_Entity_ID__c IN : setBOTEntityIds LIMIT 50000])
        {
        	mapAccountIds.put(Integer.valueOf(objAccount.BOT_Entity_ID__c), objAccount.Id);
        }
        
        //Retrieving SFDC Formulary product record by comparing BOT Formulary Product ID and put in the map
        mapFormularyProduct = new Map<Integer, Formulary_Products_vod__c>();
        for(Formulary_Products_vod__c objFormularyProduct : [SELECT Id, BOT_Formulary_Product_ID__c, market_vod__c FROM Formulary_Products_vod__c WHERE BOT_Formulary_Product_ID__c IN : setBOTFormularyproductIds LIMIT 50000])
        {
        	mapFormularyProduct.put(Integer.valueOf(objFormularyProduct.BOT_Formulary_Product_ID__c), objFormularyProduct);
        }
        
        //To populate BOT_Account__c, BOT_Formulary_Product__c and Market (Name) fileds of Drug Access object
        for(BOT_Drug_Access__c objDrugAccess : lstDrugAccess)
        {
            objDrugAccess.BOT_Account__c = mapAccountIds.get(Integer.valueOf(objDrugAccess.BOT_Entity_ID__c));
            objFormularyProduct1 = mapFormularyProduct.get(Integer.valueOf(objDrugAccess.BOT_Formulary_Product_ID__c));
            objDrugAccess.BOT_Formulary_Product__c = objFormularyProduct1.Id;
            objDrugAccess.Name = objFormularyProduct1.Market_vod__c;
        }
    }
}