force-app/main/default/objects/Benefit_Design_vod__c/fields/BOT_Formulary_Name__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Name__c</fullName>
    <description>This field is used to store the name field value. Because Benefit design (Formulary) name contains more than 80 characters. But the standard name field allows a maximum of 80 characters only. So we are using this field to store the complete name. A workflow rule is used to update the standard name field by using this field value.</description>
    <label>Formulary Name Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Design_vod__c/fields/Type_vod__c.field-meta.xml
<CustomField>
    <fullName>Type_vod__c</fullName>
    <description>The value in the type field (Commercial, VA, Medicaid, etc.) is cascaded down to the Benefit Design Lines and controls what Status and Restrictions are valid. If this type field is changed, it will cascade down to the Benefit Design Lines.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Medicaid</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>DOD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/BOT_Coverage_Policy__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the coverage policy details and having a lookup relationship with Account.</description>
    <label>Coverage Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverage Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <description>Master-Detail relationship to the account object.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Coverage policy</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Channel__c.field-meta.xml
<CustomField>
    <fullName>BOT_Channel__c</fullName>
    <description>For channel selection neither commercial or medicate</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Indication__c.field-meta.xml
<CustomField>
    <fullName>BOT_Indication__c</fullName>
    <label>Indication</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Coverage_Policy__c/fields/BOT_Score__c.field-meta.xml
<CustomField>
    <fullName>BOT_Score__c</fullName>
    <label>Score</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/BOT_Pharmacy_Service__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is Used to store the pharmacy services records and having a lookup relationship with Account.</description>
    <label>Pharmacy Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacy Services</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to Account. SFDC Account ID will be populated here.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pharmacy Services</relationshipLabel>
    <relationshipName>Pharmacy_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_Channel__c.field-meta.xml
<CustomField>
    <fullName>BOT_Channel__c</fullName>
    <description>To store the Channel like Commercial, Employer, Tricare etc.</description>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_PBM_Name__c.field-meta.xml
<CustomField>
    <fullName>BOT_PBM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to Account. SFDC PBM Account ID will be populated here.</description>
    <label>PBM Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pharmacy Services</relationshipLabel>
    <relationshipName>Pharmacy_Services_PBM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Pharmacy_Service__c/fields/BOT_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>BOT_Provider_Name__c</fullName>
    <description>To store other provider name</description>
    <label>Provider Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/BOT_Plan_Product__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the Plan product information and having a lookup relationship with Account.</description>
    <label>Plan Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <description>Master-detail relationship to Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plan Products</relationshipLabel>
    <relationshipName>Plan_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Channel__c.field-meta.xml
<CustomField>
    <fullName>BOT_Channel__c</fullName>
    <description>Used to store the selection channel</description>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Tricare</fullName>
            </value>
            <value>
                <fullName>PBM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Formulary_Type_Used__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Type_Used__c</fullName>
    <description>Used to store the Formulary type used for this product</description>
    <label>Formulary Type Used</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Product_Lives_Rx__c.field-meta.xml
<CustomField>
    <fullName>BOT_Product_Lives_Rx__c</fullName>
    <description>Used to store the Rx lives covered by this product.</description>
    <label>Product Lives Rx</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>BOT_Product_Name__c</fullName>
    <description>This field is used to store the name field value. Because Plan product name contains more than 80 characters. But the standard name field allows a maximum of 80 characters only. So we are using this field to store the complete name. A workflow rule is used to update the standard name field by using this field value.</description>
    <label>Product Name Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>BOT_Product_Type__c</fullName>
    <description>Used to store the product type</description>
    <label>Product Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Product_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Product_Type_ID__c</fullName>
    <description>Used to store BOT product type ID</description>
    <label>Product Type ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BOT_Account_Summary_Extn.cls
/*
Name			: BOT_Account_Summary_Extn
Created date	: 08/08/2018
Created by		: Sreenivasulu Adipudi
Description		: This class is written by BusinessOne Technologies Inc. It is an extension for BOT_Account_Summary_View Visualforce page.
*/
public with sharing class BOT_Account_Summary_Extn 
{
	ID accountId;														//To store the ID of selected Account
    //Public String selectedChannel {get;set;}							//To store channel selected by the user
    //Public List<BOT_Plan_Product__c> lstPlanProducts {get;set;}			//To store the plan product records
    //Public List<Benefit_Design_vod__c> lstPlanFormulary {get;set;}		//To store the formulary records
    //Public List<BOT_Pharmacy_Service__c> lstPharmacyService {get;set;}	//To store the pharmacy services records
    Public List<BOT_Coverage_Policy__c> lstCoveragePolicy {get;set;}	//To store the coverage policy records
    //Set<String> setChannels = new Set<String>();						//To store uniquee channels
    
    //Constructor
    public BOT_Account_Summary_Extn(ApexPages.StandardController controller)
    {
    	accountId = controller.getId();    
    	//To get all the plan product, plan formulary records associated with selected Account
        //if(accountId != Null)
        {
        	initialRetrieve();
        }
		/*if(lstPlanProducts.size() > 0 && lstPlanProducts != null)
        {
            //Eliminating repeated channels
            for(BOT_Plan_Product__c objPlanProduct : lstPlanProducts)
            {
            	setChannels.add(objPlanProduct.BOT_Channel__c);    
            }
        }*/
	}
    
    public void initialRetrieve()
    {
    	//To get Plan products records
        /*
        lstPlanProducts = [SELECT Id, BOT_Channel__c, BOT_Product_Name__c, BOT_Product_Type__c, BOT_Product_Type_ID__c, BOT_Formulary_Type_Used__c, BOT_Product_Lives_Rx__c 
                           FROM BOT_Plan_Product__c 
                           WHERE BOT_Account__c =: accountId ORDER BY BOT_Channel__c, BOT_Product_Type_ID__c, BOT_Product_Lives_Rx__c DESC NULLS LAST 
                           LIMIT 50000];
        
        //To get Plan formulary records
        lstPlanFormulary = [SELECT Id, Type_vod__c, BOT_Formulary_Name__c, Lives_vod__c 
                            FROM Benefit_Design_vod__c 
                            WHERE Account_vod__c =: accountId ORDER BY Type_vod__c, Lives_vod__c DESC NULLS LAST 
                            LIMIT 50000];
        
        //To get Pharmacy Service records
        lstPharmacyService = [SELECT Id, Name, BOT_Channel__c, BOT_Account__c, BOT_PBM_Name__r.Name, BOT_Provider_Name__c 
                              FROM BOT_Pharmacy_Service__c 
                              WHERE BOT_Account__c =: accountId ORDER BY BOT_Channel__c, Name
                              LIMIT 50000];
		*/
        //To get Coverage policy records related to selected account
        lstCoveragePolicy = [select Id, BOT_Channel__c, Name, BOT_Score__c, BOT_Indication__c, (select Id, name from Attachments limit 2) 
                             from BOT_Coverage_Policy__c where BOT_Account__c =: accountId ORDER BY Name];
    }
    
    /*
    public void channelFilterRetrieve()
    {
        if(selectedChannel != Null)
        {
            //If the selected channel is All then get all records
            if(selectedChannel == '--ALL--')
            {
        		initialRetrieve();	
            }
            else
            {
        		//To get Plan products records filtered by selected channel
	        	lstPlanProducts = [SELECT Id, BOT_Channel__c, BOT_Product_Name__c, BOT_Product_Type__c, BOT_Product_Type_ID__c, BOT_Formulary_Type_Used__c, BOT_Product_Lives_Rx__c 
                                   FROM BOT_Plan_Product__c 
                                   WHERE BOT_Account__c =: accountId and BOT_Channel__c =: selectedChannel ORDER BY BOT_Product_Type_ID__c, BOT_Product_Lives_Rx__c DESC NULLS LAST 
                                   LIMIT 50000];
        		
                //To get Plan formulary records filtered by selected channel
        		lstPlanFormulary = [SELECT Id, Type_vod__c, BOT_Formulary_Name__c, Lives_vod__c 
                                    FROM Benefit_Design_vod__c 
                                    WHERE Account_vod__c =: accountId and Type_vod__c =: selectedChannel ORDER BY Type_vod__c, Lives_vod__c DESC NULLS LAST 
                                    LIMIT 50000];
                
                //To get Pharmacy Service records filtered by selected channel
        		lstPharmacyService = [SELECT Id, Name, BOT_Channel__c, BOT_Account__c, BOT_PBM_Name__r.Name, BOT_Provider_Name__c 
                              		  FROM BOT_Pharmacy_Service__c 
                              		  WHERE BOT_Account__c =: accountId and BOT_Channel__c =: selectedChannel ORDER BY Name
                              		  LIMIT 50000];
            }
        }
    }
    
    //Creating a dynamic picklist with channels
    public List<selectOption> getDynamicList()
    {
        List<selectOption> options = new List<selectOption>();
        if(setChannels.size()>0 && setChannels != null)
        {
        	if(setChannels.size()>1)
        	{
        		options.add(new selectOption('--ALL--','--ALL--'));
        	}
            for(String c : setChannels)
        	{
        		options.add(new selectOption(c,c));
        	}
        }
        return options;
    }
	*/
}