force-app/main/default/objects/Benefit_Design_vod__c/fields/BOT_Benefit_Design_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Benefit_Design_ID__c</fullName>
    <description>It is created by BusinessOne Technologies. It is used to store BOT Formulary ID.</description>
    <externalId>true</externalId>
    <label>Benefit Design ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BOT_Plan_Product__c/BOT_Plan_Product__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the Plan product information and having a lookup relationship with Account.</description>
    <label>Plan Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Plan_Product__c/fields/BOT_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Product_ID__c</fullName>
    <description>To store BOT Product ID. This field is used as external ID</description>
    <externalId>true</externalId>
    <label>Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BOT_Product_Formulary_JO__c/BOT_Product_Formulary_JO__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is a junction object between plan product and formulary objects. It is having Master-Detail relationship with Plan product and Plan formulary objects.</description>
    <label>Plan-Product Formulary</label>
    <nameField>
        <displayFormat>PF-{0000}</displayFormat>
        <label>S No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan-Product Formulary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Product_Formulary_JO__c/fields/BOT_Benefit_Design__c.field-meta.xml
<CustomField>
    <fullName>BOT_Benefit_Design__c</fullName>
    <description>Master-Detail relationship to Benefit Design Object.</description>
    <label>Benefit Design</label>
    <referenceTo>Benefit_Design_vod__c</referenceTo>
    <relationshipName>Benefit_Design</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Product_Formulary_JO__c/fields/BOT_Benefit_Design_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Benefit_Design_ID__c</fullName>
    <description>It is used to store the BOT formulary ID. It is used for BOT internal reference only.</description>
    <label>Benefit Design ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOT_Product_Formulary_JO__c/fields/BOT_Plan_Product__c.field-meta.xml
<CustomField>
    <fullName>BOT_Plan_Product__c</fullName>
    <description>Master-Detail relationship to Plan product object</description>
    <label>Plan Product</label>
    <referenceTo>BOT_Plan_Product__c</referenceTo>
    <relationshipLabel>Plan Formulary</relationshipLabel>
    <relationshipName>Plan_Product</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOT_Product_Formulary_JO__c/fields/BOT_Plan_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>BOT_Plan_Product_ID__c</fullName>
    <description>It is used to store the plan product ID. It is used for BOT internal reference only.</description>
    <label>Plan Product ID</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BOT_ProductFormularyTriggerHandler.cls
/*
Name			: BOT_ProductFormularyTriggerHandler
Created by		: Sreenivasulu A
Created date	: 05-NOV-2018
Overview        : It is implemented by BusinessOne Technologies Inc. It is a handler class of BOT_ProductFormularyTrigger trigger.
*/
public with sharing class BOT_ProductFormularyTriggerHandler
{
	public static void populateProductIdAndFormularyId(List<BOT_Product_Formulary_JO__c> lstProductFormulary, Set<Double> setPlanProductIds, Set<Double> setBenefitDesignIds)
    {
        Map<Double, ID> mapPlanProductIds = new Map<Double, ID>();		//Map of BOT Plan product Ids and asssociated SFDC Plan Product IDs
        Map<Double, ID> mapBenefitDesignIds = new Map<Double, ID>();	//Map of BOT Benefit design Ids and asssociated SFDC Benefit design IDs
        
        //To Retrieve SFDC Plan product Ids by comparing BOT Plan product Ids and put in the map   
        for(BOT_Plan_Product__c objPlanProduct : [select Id, BOT_Product_ID__c from BOT_Plan_Product__c where BOT_Product_ID__c in : setPlanProductIds])
        {
            mapPlanProductIds.put(objPlanProduct.BOT_Product_ID__c, objPlanProduct.Id);
        }
        
        //To Retrieve SFDC Benefit Design Ids by comparing BOT Benefit Design Ids and put in the map 
        for(Benefit_Design_vod__c objBenefitDesign : [select Id, BOT_Benefit_Design_ID__c from Benefit_Design_vod__c where BOT_Benefit_Design_ID__c in : setBenefitDesignIds])
        {
        	mapBenefitDesignIds.put(objBenefitDesign.BOT_Benefit_Design_ID__c, objBenefitDesign.Id);
        }
        
        //To populate BOT_Plan_Product__c and BOT_Benefit_Design__c fileds
        for(BOT_Product_Formulary_JO__c objProductFormulary : lstProductFormulary)
        {
            objProductFormulary.BOT_Plan_Product__c = mapPlanProductIds.get(objProductFormulary.BOT_Plan_Product_ID__c);
            objProductFormulary.BOT_Benefit_Design__c = mapBenefitDesignIds.get(objProductFormulary.BOT_Benefit_Design_ID__c);
        }
    }
}