force-app/main/default/objects/Benefit_Design_Line_vod__c/fields/BOT_Market__c.field-meta.xml
<CustomField>
    <fullName>BOT_Market__c</fullName>
    <description>To pull market from the Formulary Product object</description>
    <formula>TEXT(Product_vod__r.Market_vod__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Design_Line_vod__c/fields/Competitor_vod__c.field-meta.xml
<CustomField>
    <fullName>Competitor_vod__c</fullName>
    <description>Indicates whether the product is a competitor product. If true, product is a competitor; otherwise it is a company product. Evaluated from the Competitor_vod field in Formulary_Product_vod object. Not visible in the page layout - used only by the application.</description>
    <formula>Product_vod__r.Competitor_vod__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Competitor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Benefit_Design_Line_vod__c/fields/Restrictions_Source_vod__c.field-meta.xml
<CustomField>
    <fullName>Restrictions_Source_vod__c</fullName>
    <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Restrictions field is filled in, it will override the Restrictions (Source) field in the display of the formulary control.</description>
    <label>Restrictions (Source)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>QL</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>ST</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Design_Line_vod__c/fields/Status_Source_vod__c.field-meta.xml
<CustomField>
    <fullName>Status_Source_vod__c</fullName>
    <description>This data is meant to be loaded and refreshed by the customer from the source data provider, such as MediMedia and not changed by end users. If the Status field is filled in, it will override the Status (Source) field in the display of the formulary control.</description>
    <label>Status (Source)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved with Restrictions</fullName>
            </value>
            <value>
                <fullName>Covered</fullName>
            </value>
            <value>
                <fullName>Non-Formulary</fullName>
            </value>
            <value>
                <fullName>Non-Formulary / Covered</fullName>
            </value>
            <value>
                <fullName>Non-Formulary / Higher Copay</fullName>
            </value>
            <value>
                <fullName>Non-Formulary / Not Reimbursed</fullName>
            </value>
            <value>
                <fullName>Non-Formulary / Prior Authorization</fullName>
            </value>
            <value>
                <fullName>Non-Formulary / Unknown</fullName>
            </value>
            <value>
                <fullName>Non-Preferred</fullName>
            </value>
            <value>
                <fullName>Not Covered</fullName>
            </value>
            <value>
                <fullName>Not Listed / Covered</fullName>
            </value>
            <value>
                <fullName>Not Listed / Higher Copay</fullName>
            </value>
            <value>
                <fullName>Not Listed / Not Reimbursed</fullName>
            </value>
            <value>
                <fullName>Not Listed / Prior Authorization</fullName>
            </value>
            <value>
                <fullName>Not Listed / Unknown</fullName>
            </value>
            <value>
                <fullName>Not Reimbursed</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Prior Authorization</fullName>
            </value>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
            <value>
                <fullName>Tier 5</fullName>
            </value>
            <value>
                <fullName>Tier 6</fullName>
            </value>
            <value>
                <fullName>Tier 7</fullName>
            </value>
            <value>
                <fullName>Tier 8</fullName>
            </value>
            <value>
                <fullName>Tier 9</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOT_Configuration_Value__mdt/BOT_Configuration_Value__mdt.object-meta.xml
<CustomObject>
    <description>This object is created by BusinessOne technologies Inc. It is used to store the configuration values like the default market, default pharmacy service, Endpoint URL etc</description>
    <label>BOT_Configuration Value</label>
    <pluralLabel>BOT_Configuration Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/BOT_Configuration_Value__mdt/fields/BOT_Value__c.field-meta.xml
<CustomField>
    <fullName>BOT_Value__c</fullName>
    <description>Used to hold the value.</description>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BOT_BenefitDesignViewCtrl.cls
/*
Name            : BOT_BenefitDesignViewCtrl
Created by      : Sreenivasulu Adipudi
Created date    : 05/22/2019
Description     : It is a controller class for BOT_BenefitDesignView lightning component. It is used to pull the benefitdesignLine data for the selected Benefitdesign.
*/
public class BOT_BenefitDesignViewCtrl {
    @AuraEnabled
    public static WrapperClass getBenefitDesignLine(Id benefitDesignId){
        Set<String> setMarket = new Set<String>();
        WrapperClass lstRecords = new WrapperClass();
        
        lstRecords.strDefaultMarket = [SELECT BOT_Value__c FROM BOT_Configuration_Value__mdt WHERE DeveloperName = 'BOT_Default_Market' LIMIT 1].BOT_Value__c;
           
        lstRecords.lstBenefitDesignLine = [SELECT Id, BOT_Market__c, Product_vod__r.Name, Product_vod__r.Competitor_vod__c, Status_Source_vod__c, 
                                           Restrictions_Source_vod__c, Copay_Source_vod__c, Notes_Source_vod__c FROM Benefit_Design_Line_vod__c 
                                           WHERE Benefit_Design_vod__c =: benefitDesignId ORDER BY Product_vod__r.Name];

        for(Benefit_Design_Line_vod__c objBenefitDesignLine : lstRecords.lstBenefitDesignLine)
        {
            setMarket.add(objBenefitDesignLine.BOT_Market__c);
        }
        
        if(setMarket.contains(lstRecords.strDefaultMarket))
        {
        	lstRecords.lstBenefitDesignLineFiltered = [SELECT Id, BOT_Market__c, Product_vod__r.Name, Product_vod__r.Competitor_vod__c, Status_Source_vod__c, 
                                           Restrictions_Source_vod__c, Copay_Source_vod__c, Notes_Source_vod__c FROM Benefit_Design_Line_vod__c 
                                           WHERE Benefit_Design_vod__c =: benefitDesignId AND BOT_Market__c =: lstRecords.strDefaultMarket 
                                           ORDER BY Product_vod__r.Name];
        }
        else
        {
        	lstRecords.lstBenefitDesignLineFiltered.addAll(lstRecords.lstBenefitDesignLine);
        }
        
        lstRecords.lstMarket = new List<String>();
        if(setMarket.size() > 1)
        {
            lstRecords.lstMarket.add('All');
            lstRecords.lstMarket.add('All Company Products');
        }
        lstRecords.lstMarket.addAll(setMarket);
        lstRecords.lstMarket.sort();
        
        return lstRecords;
    }
    
    public class WrapperClass {
        @AuraEnabled public List<String> lstMarket {get;set;}
        @AuraEnabled public String strDefaultMarket {get;set;}
        @AuraEnabled public List<Benefit_Design_Line_vod__c> lstBenefitDesignLine {get;set;}
        @AuraEnabled public List<Benefit_Design_Line_vod__c> lstBenefitDesignLineFiltered {get;set;}
    }
}