force-app/main/default/objects/BOT_Drug_Access__c/BOT_Drug_Access__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the drug access percentage.</description>
    <label>Drug Access</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drug Access</relationshipLabel>
    <relationshipName>Drug_Access</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BOT_AccountDrugAccessltng.cls
/*
Name 			: BOT_AccountDrugAccessltng
Created by 		: Sreenivasulu Adipudi
Created date 	: 06/03/2019
Description 	: It is a controller class for BOT_AccountDrugAccess lightning component. It is used to get the markets dynamically.
*/
public class BOT_AccountDrugAccessltng {
	@AuraEnabled
    public static List<String> getMarkets(Id accountId){
        List<String> lstMarkets = new List<String>();
       	AggregateResult[] aggRes = [SELECT Name FROM BOT_Drug_Access__c GROUP BY Name, BOT_Account__c HAVING BOT_Account__c =: accountId ORDER BY Name]; 
        system.debug('accountId : '+accountId);
        system.debug('Before loop : '+aggRes);
        
        for(AggregateResult res : aggRes)
        {
        	lstMarkets.add(String.valueOf(res.get('Name')));
        }
        system.debug('outside loop : '+lstMarkets);
        if(lstMarkets != null && lstMarkets.size() > 1)
        {
            lstMarkets.add(0,'All');
        }
        system.debug('lstMarkets : '+lstMarkets);
        return lstMarkets;
    }
}