force-app/main/default/objects/BOT_Drug_Access__c/BOT_Drug_Access__c.object-meta.xml
<CustomObject>
    <description>(BOT) It is created by BusinessOne Technologies Inc. It is used to store the drug access percentage.</description>
    <label>Drug Access</label>
    <nameField>
        <label>Market</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drug Access</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Access_Percentage__c.field-meta.xml
<CustomField>
    <fullName>BOT_Access_Percentage__c</fullName>
    <description>Used to store the Access Perchentage</description>
    <label>Access Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Account__c.field-meta.xml
<CustomField>
    <fullName>BOT_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to Account.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drug Access</relationshipLabel>
    <relationshipName>Drug_Access</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Drug_Status__c.field-meta.xml
<CustomField>
    <fullName>BOT_Drug_Status__c</fullName>
    <description>To store the drug status.</description>
    <label>Drug Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOT_Drug_Access__c/fields/BOT_Formulary_Product__c.field-meta.xml
<CustomField>
    <fullName>BOT_Formulary_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup relationship to formulary product (Drug) object.</description>
    <label>Drug Name</label>
    <referenceTo>Formulary_Products_vod__c</referenceTo>
    <relationshipLabel>Drug Access</relationshipLabel>
    <relationshipName>Drug_Access</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BOT_DrugAccessDashboardDynamicExtn.cls
public class BOT_DrugAccessDashboardDynamicExtn 
{
    public static ID accountID;
    public static Map<String, Map<String,Decimal>> data {get;set;}
        
    public BOT_DrugAccessDashboardDynamicExtn(ApexPages.StandardController controller)
    {
        accountID = '001m000000mukrc';	//controller.getId();
    }

    public static Map<String, Map<String,Decimal>> getChartData(){
    	
        data = new Map<String, Map<String,Decimal>>();
    	
    	for(BOT_Drug_Access__c objDrugAccess : [SELECT Id, BOT_Formulary_Product__r.Name, BOT_Drug_Status__c, BOT_Access_Percentage__c FROM BOT_Drug_Access__c WHERE BOT_Account__c =: accountID]) 
        {
            //data.putData(objDrugAccess.BOT_Formulary_Product__r.Name, objDrugAccess.BOT_Drug_Status__c, objDrugAccess.BOT_Access_Percentage__c);
        }
        return data;
	}
 
	private static void putData(String drugName, String status, Decimal accessPercentage){
    	Map<String,Decimal> statusGroup = new Map<String,Decimal>();
    	if(data.containsKey(drugName)){
        	statusGroup = data.get(drugName);
    	}
    	statusGroup.put(status, accessPercentage);
    	data.put(drugName, statusGroup);
    }
}